name: overscript
description: OverScript
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  # cool_alert: ^1.1.0
  # cool_alert: 
  #   git: https://github.com/veoxer/flutter_cool_alert.git
  # cool_alert: 
  #   path: ../flutter_cool_alert
  dog: ^1.4.0
  equatable: ^2.0.3
  fialogs: ^2.0.4
  file_selector: ^0.8.3
  file_selector_linux: ^0.0.2+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_form_builder: ^7.0.0
  flutter_localizations:
    sdk: flutter
  form_builder_validators: ^7.3.0
  hydrated_bloc: ^8.0.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  settings_ui: ^2.0.2
  streaming_shared_preferences: ^2.0.0
  uuid: ^3.0.5

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  json_serializable: ^6.0.1
  

flutter:
  uses-material-design: true
  generate: true
