name: overscript

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: ./.github/actions/flutter
        

      - name: Install Dependencies
        run: |
          flutter pub get

      - name: Run Tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random --reporter json > reports.json

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Flutter Tests
          path: reports.json
          reporter: flutter-json
      
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: coverage/lcov.*.info
          minimum-coverage: 0
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: .
        
